all:
  children:
    kvm_tacc:
      vars:
        ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p cc@{{ lookup('env', 'FLOATING_IP_KVM_TACC') }}"

      hosts:
        node1:
          ansible_host: 192.168.1.11
          ansible_user: cc
        node2:
          ansible_host: 192.168.1.12
          ansible_user: cc
        node3:
          ansible_host: 192.168.1.13
          ansible_user: cc

      children:
        kube_control_plane:
          hosts:
            node1:
            node2:
        kube_node:
          hosts:
            node1:
            node2:
            node3:
        etcd:
          hosts:
            node1:
            node2:
            node3:
        k8s_cluster:
          children:
            kube_control_plane:
            kube_node:
        calico_rr:
          hosts: {}

    chi_uc:
      vars:
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=cc@{{ lookup('env', 'FLOATING_IP_CHI_UC') }}"
      hosts:
        gpu_node:
          ansible_host: 192.168.1.10
          ansible_user: cc

