apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  #volumeName: object-store
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 660Mi
  storageClassName: standard

---

apiVersion: v1
kind: Pod
metadata:
  name: minio
  labels:
    app: minio
    set: training
spec:
  containers:
    - name: minio
      image: minio/minio
      args: ["server", "/data", "--console-address", ":9001"]
      env:
        - name: MINIO_ROOT_USER
          value: minioadmin
        - name: MINIO_ROOT_PASSWORD
          value: minioadmin123
      ports:
        - containerPort: 9000  # S3 API
        - containerPort: 9001  # Web UI
      volumeMounts:
        - name: object-store
          mountPath: /data
          subPath: minio
  volumes:
    - name: object-store
      persistentVolumeClaim:
        claimName: minio

---

apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
  type: ClusterIP

