apiVersion: v1
kind: Pod
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  containers:
    - name: mlflow
      image: ghcr.io/mlflow/mlflow:v2.20.2
      ports:
        - containerPort: 8000
      env:
        - name: MLFLOW_TRACKING_URI
          value: http://0.0.0.0:8000
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio:9000
        - name: AWS_ACCESS_KEY_ID
          value: minioadmin
        - name: AWS_SECRET_ACCESS_KEY
          value: minioadmin123
      command: ["/bin/sh", "-c"]
      args:
        - >
          pip install psycopg2-binary boto3 &&
          mlflow server 
          --backend-store-uri postgresql://mlflowuser:mlflowuser123@postgres:5432/mlflowdb 
          --artifacts-destination s3://mlflow-artifacts/ 
          --serve-artifacts 
          --host 0.0.0.0 
          --port 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP # or NodePort/ClusterIP based on your needs

