---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triton
  namespace: staging
  annotations:
    csi-rclone/storage-path: triton
    csi-rclone/umask: "022"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 90Gi
  storageClassName: rclone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton
  namespace: staging
  labels:
    app: triton
spec:
  selector:
    matchLabels:
      app: triton
  replicas: 1
  template:
    metadata:
      labels:
        app: triton
    spec:
      containers:
        - name: triton
          image: nvcr.io/nvidia/tritonserver:22.08-py3
          args:
            - tritonserver
            - --model-repository=/models
            - --strict-model-config=false
          ports:
            - containerPort: 8000  # HTTP
            - containerPort: 8001  # gRPC
            - containerPort: 8002  # Metrics
          resources:
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: block-store
              mountPath: /models
      volumes:
        - name: block-store
          persistentVolumeClaim:
            claimName: triton
---
apiVersion: v1
kind: Service
metadata:
  name: triton
  namespace: staging
spec:
  selector:
    app: triton
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 8001
      targetPort: 8001
    - name: metrics
      port: 8002
      targetPort: 8002
  type: ClusterIP
  externalIPs:
    - 192.168.1.10
