name: pdf_to_text

volumes:
  raw-data:

services:
  extract-data:
    environment:
      - FILE_URL=${FILE_URL:-unset}
    container_name: etl_extract_data
    image: python-gsutil:3.11
    user: root
    volumes:
      - raw-data:/data
      - /mnt/object/raw-data:/data-obj
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e
        cp /data-obj/$${FILE_URL}.tar .
        ls
        tar -xvf $${FILE_URL}.tar
        rm -rf $${FILE_URL}.tar

  transform-data:
    container_name: etl_2_transform_data
    environment:
      - FILE_URL=${FILE_URL:-unset}
    image: python-gsutil:3.11
    volumes:
      - raw-data:/data
      - ./:/code_files
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e

        mkdir "text_$${FILE_URL}"
        python3 ../code_files/pdf-to-text-from-folder.py ./$${FILE_URL} ./"text_$${FILE_URL}" 8
        rm -rf $${FILE_URL}
        tar -cvf "text_$${FILE_URL}.tar" text_$${FILE_URL}
        rm -rf text_$${FILE_URL}

  load-data:
    container_name: etl_2_load_data
    environment:
      - FILE_URL=${FILE_URL:-unset}
    image: rclone/rclone:latest
    volumes:
      - raw-data:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |

        rclone copy ./"text_$${FILE_URL}.tar" chi_tacc:object-persist-rg5073-test/text-files-data \
        --progress \
        --transfers=32 \
        --checkers=16 \
        --multi-thread-streams=4 \
        --fast-list

        rm -rf "text_$${FILE_URL}.tar"


