apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rclone
provisioner: csi-rclone
parameters:
  remote: chi_tacc
  pathPattern: "${.PVC.annotations.csi-rclone/storage-path}"
reclaimPolicy: Delete
volumeBindingMode: Immediate

