
chi_uc:
  vars:
    ansible_ssh_common_args: >- 
      -o StrictHostKeyChecking=no 
      -o UserKnownHostsFile=/dev/null 
      -o ForwardAgent=yes 
      -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p cc@{{ lookup('env', 'FLOATING_IP_CHI_UC') }}"
  hosts:
    gpunode1:
      ansible_host: 192.168.1.10
      ansible_user: cc
      ip: 192.168.1.10
      access_ip: 192.168.1.10

cluster:
  children:
    kube_control_plane:
      hosts:
        gpunode1:
    kube_node:
      hosts:
        gpunode1:
    etcd:
      hosts:
        gpunode1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
