apiVersion: v1
kind: PersistentVolume
metadata:
  name: raw-data-pv
  namespace: argo
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1  
  hostPath:
    path: /mnt/data/raw-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raw-data-pvc
  namespace: argo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual 

