name: pdf-to-text

volumes:
  project-22-pdf-to-text:

services:
  extract-data:
    image: rclone/rclone:latest
    user: root
    volumes:
      - project-22-pdf-to-text:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    working_dir: /data
    command:
      - -c
      - |
        set -e
        
        sudo mkdir -p /mnt/object
        sudo chown -R cc /mnt/object
        sudo chgrp -R cc /mnt/object
        rclone mount chi_tacc:object-persist-project-22 /mnt/object --read-only --allow-other --daemon
        ls /mnt/object
        ls /mnt/object/raw-data/ > tar_files_list.txt
        cat tar_files_list.txt

  # transform-data:
  #   container_name: etl_transform_data
  #   image: python:3.11
  #   volumes:
  #     - food11:/data
  #   working_dir: /data/Food-11
  #   command:
  #     - bash
  #     - -c
  #     - |
  #       set -e

  #       python3 -c '
  #       import os
  #       import shutil

  #       dataset_base_dir = "/data/Food-11"
  #       subdirs = ["training", "validation", "evaluation"]
  #       classes = [
  #           "Bread", "Dairy product", "Dessert", "Egg", "Fried food",
  #           "Meat", "Noodles/Pasta", "Rice", "Seafood", "Soup", "Vegetable/Fruit"
  #       ]

  #       for subdir in subdirs:
  #           dir_path = os.path.join(dataset_base_dir, subdir)
  #           if not os.path.exists(dir_path):
  #               continue

  #           for i, class_name in enumerate(classes):
  #               class_dir = os.path.join(dir_path, f"class_{i:02d}")
  #               os.makedirs(class_dir, exist_ok=True)
  #               for f in os.listdir(dir_path):
  #                   if f.startswith(f"{i}_"):
  #                       shutil.move(
  #                           os.path.join(dir_path, f),
  #                           os.path.join(class_dir, f)
  #                       )
  #       '

  #       echo "Listing contents of /data/Food-11 after transform stage:"
  #       ls -l /data/Food-11

  # load-data:
  #   container_name: etl_load_data
  #   image: rclone/rclone:latest
  #   volumes:
  #     - food11:/data
  #     - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
  #   entrypoint: /bin/sh
  #   command:
  #     - -c
  #     - |
  #       if [ -z "$RCLONE_CONTAINER" ]; then
  #         echo "ERROR: RCLONE_CONTAINER is not set"
  #         exit 1
  #       fi
  #       echo "Cleaning up existing contents of container..."
  #       rclone delete chi_tacc:$RCLONE_CONTAINER --rmdirs || true

  #       rclone copy /data/Food-11 chi_tacc:$RCLONE_CONTAINER \
  #       --progress \
  #       --transfers=32 \
  #       --checkers=16 \
  #       --multi-thread-streams=4 \
  #       --fast-list

  #       echo "Listing directories in container after load stage:"
  #       rclone lsd chi_tacc:$RCLONE_CONTAINER