apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: mlflow
data:
  init.sql: |
    CREATE ROLE mlflowuser WITH LOGIN PASSWORD 'mlflow@123';
    CREATE DATABASE mlflowdb OWNER mlflowuser;
    GRANT CONNECT ON DATABASE mlflowdb TO mlflowuser;
    \c mlflowdb;
    GRANT USAGE ON SCHEMA public TO mlflowuser;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO mlflowuser;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mlflowuser;

