apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  namespace: mlflow 
  labels:
    app: postgres
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1
  hostPath:
    path: /mnt/block/volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: mlflow 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
  selector:
    matchLabels:
      app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mlflow
  labels:
    app: mlflow
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: node1
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: block-store
              mountPath: /var/lib/postgresql/data 
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: block-store
          persistentVolumeClaim:
            claimName: postgres
        - name: init-script 
          configMap:
            name: postgres-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mlflow 
spec:
  selector:
    app: postgres
  ports:
    - name: db
      port: 5432
      targetPort: 5432
  externalIPs:
    - {{ .Values.global.externalIP }}

  #---
  #apiVersion: v1
  #kind: Service
  #metadata:
  #  name: postgres-nodeport
  #spec:
  #  selector:
  #    app: postgres
  #  ports:
  #    - name: db
  #      port: 5432
  #      targetPort: 5432
  #      nodePort: 30002
  #  type: NodePort
  #
