apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: mlflow
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    
    scrape_configs:
      - job_name: minio-job
        bearer_token: ""
        metrics_path: /minio/v2/metrics/cluster
        scheme: http
        static_configs:
          - targets: ['minio:9000']
      - job_name: 'ray-head'
        static_configs:
          - targets: ['ray-head:8090']
        
