apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: mlflow
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    
    scrape_configs:
      - job_name: minio-job
        bearer_token: ""
        metrics_path: /minio/v2/metrics/cluster
        scheme: http
        static_configs:
          - targets: ['minio:9000']
      - job_name: 'ray-head'
        static_configs:
          - targets: ['192.168.1.11:8090']
      - job_name: 'serve-testing'
        metrics_path: /health
        scheme: http
        static_configs:
          - targets: ['{{ .Values.global.chi_uc_IP }}:8001']
