apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: mlflow
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    
    scrape_configs:
      - job_name: 'minio'
        static_configs:
          - targets: ['minio:9001']   
