apiVersion: v1
kind: Endpoints
metadata:
  name: ray-head
  namespace: mlflow
subsets:
  - addresses:
      - ip: 192.168.1.11
    ports:
      - port: 8080
        name: metrics
      - port: 8265
        name: dashboard
      - port: 10001
        name: client
---
apiVersion: v1
kind: Service
metadata:
  name: ray-head
  namespace: mlflow
spec:
  ports:
    - name: http
      port: 8080
      targetPort: metrics
    - name: dashboard
      port: 8265
      targetPort: dashboard
    - name: client
      port: 10001
      targetPort: client
  externalIPs:
    - {{ .Values.rayhead.externalIP }}
