name: prepare-postgres-data

volumes:
  raw-data:

services:
  extract-data:
    container_name: etl_4_extract_data
    image: python-gsutil:3.11
    user: root
    volumes:
      - raw-data:/data
      - /mnt/object/:/data-obj
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e
        cp -r /data-obj/meta-data/arxiv_cleaned_v1.csv .

  transform-data:
    container_name: etl_4_transform_data
    environment:
      - DATA_TO_PROCESS=${DATA_TO_PROCESS:-unset}
      - META_DATA_TABLE=${META_DATA_TABLE:-unset}
      - CHUNKS_DATA_TABLE=${CHUNKS_DATA_TABLE:-unset}
    image: python-gsutil:3.11
    volumes:
      - raw-data:/data
      - ./:/dir_data
      - /mnt/object/:/data-obj
      # - /mnt/object/$${DATA_TO_PROCESS}:/req-data
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e

        ls ../dir_data
        mkdir -p /req-data
        cp -r /data-obj/$${DATA_TO_PROCESS}/* /req-data

        cd ../dir_data
        python3 prepare_postgres_data.py $${META_DATA_TABLE} $${CHUNKS_DATA_TABLE}
        # python3 prepare_postgres_data.py

